### ISSUE TITLE
deep_cover/builtin_takeover and SimpleCov configuration

### ISSUE THREAD

**Issue by tleish** [deep-cover/deep-cover#60]
I have several filters  SimpleCov configured to track one group of files and ignore others.  It appears when using `deep_cover/builtin_takeover` it does not take this configuration into account.  Is this correct?  Is there a correct way of telling DeepCover to look at the configuration of SimpleCov?

**Comment by MaxLap** [comment]
You are correct that `DeepCover` doesn't look at `SimpleCov`'s configuration. This is because `DeepCover` is doing things at a lower level than `SimpleCov` and now actually interacting with it at all.

Since you use builtin_takeover, the filters should get applied by `SimpleCov` when it is generating the report and the report would be as you would expect. Is that not the case?

The only side effect of DeepCover not filtering the files is that it will process more files and so have a somewhat higher overhead. If that is really an issue, then you can use `paths` in the config to pass in an array of globs for which files should DeepCover consider.
